### PR TITLE
Fix urlparse imports for python3 compatibility

### PR DESCRIPTION
**Pull request by srowe**
Signed-off-by: Simon Rowe <simon.rowe@eu.citrix.com>

### CODE REVIEW

**Comment by mseri** [comment]
The PR broke the tests. Please do not use wildcard imports, we don't know if there is any of our functions that has overlapping names.

**Comment by mseri** [comment]
```
======================================================================
ERROR: Well-formed BitBucket URLs are parsed correctly
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python2.7_with_system_site_packages/local/lib/python2.7/site-packages/mock/mock.py", line 1305, in patched
    return func(*args, **keywargs)
  File "/home/travis/build/xenserver/planex/tests/test_repository.py", line 26, in test_urls
    repo = planex.repository.Repository(tcase['URL'])
  File "/home/travis/build/xenserver/planex/planex/repository.py", line 33, in __init__
    self.parsers[self.url.netloc](self)
  File "/home/travis/build/xenserver/planex/planex/repository.py", line 158, in parse_bitbucket
    query_dict = parse_qs(self.url.query)
NameError: global name 'parse_qs' is not defined
```

```
planex/cmd/pin.py:100:17: E124 closing bracket does not match visual indentation
                ).get("prefix", None)
```

**Comment by srowe** [comment]
I'll try another approach but I can't find any compat approach that preserves `urlparse` as a module.

**Comment by mseri** [comment]
I am happy to use the new urlparse and require a compat layer for python 2.7

**Comment by mseri** [comment]
The pylint issue with six.moves is a known bug, we can silence it with `# pylint: disable=relative-import`

**Comment by mseri** [comment]
The remaining failure is a known issue

**Pull request merged**
