### PR TITLE
makesrpm: add --keeptmp

### PR DESCRIPTION
**Pull request by srowe**
Add option to retain the directory containing the autogenerated
specfile.

Signed-off-by: Simon Rowe <simon.rowe@eu.citrix.com>

### CODE REVIEW

**Comment by lindig** [comment]
Looks fine to me.

**Comment by euanh** [comment]
@srowe: Could you please fix the pylint/pep8 errors?

**Comment by srowe** [comment]
I don't see any pylint errors

**Comment by euanh** [comment]
@srowe: https://travis-ci.org/xenserver/planex/builds/143327873

**Pull request merged**
