### PR TITLE
Remove unused debianization code

### PR DESCRIPTION
**Pull request by euanh**
Remove leftover code for supporting automatic Debian package conversion.   All the original code is still available in the debian branch.
Removing this code allows us to tighten up the pylint configuration.

### CODE REVIEW

**Comment by lindig** [comment]
The code in rpmextra doesn't look Debian specific - this was a little surprise for me as an outsider.

**Comment by euanh** [comment]
@lindig: It was only used to support the script which made debs from rpms.

**Comment by lindig** [comment]
> One of my most productive days was throwing away 1000 lines of code. — Ken Thompson

In this light: looks good to me.

**Comment by lindig** [comment]
Time to :shipit: before more changes pile on.

**Pull request merged**
