### PR TITLE
Default to MD5 if srpm.filedigestalgo isn't set

### PR DESCRIPTION
**Pull request by johnelse**

### CODE REVIEW

**Comment by thomassa** [comment]
Why MD5?

**Comment by johnelse** [comment]
This code is only to log the algorithm that's already been used. Older versions of the library don't set the `filedigestalgo` field, but we found MD5 had been used so was a sensible default.

**Comment by euanh** [comment]
MD5 was the default digest algorithm in RPM 4.4 and earlier.  In RPM 4.6 the digest algorithm became configurable: http://rpm.org/wiki/releases/4.6

**Comment by thomassa** [comment]
Makes sense then.

**Pull request merged**
