### PR TITLE
Add bash completion for all entry points

### LINKED ISSUE #134: Add bash completion support
http://tldp.org/LDP/abs/html/tabexpansion.html

### PR DESCRIPTION
**Pull request by simonjbeaumont**
Fixes #134.

Signed-off-by: Si Beaumont <simon.beaumont@citrix.com>

### CODE REVIEW

**Comment by simonjbeaumont** [comment]
Query packaging... There's a python module dependency we need to install. I don't think it can be added to the spec file cos it's not in the normal yum repos. It is available in `pip` and I have added it to `requirements.txt` so it will be installed by Travis. However, will this be automagically packaged up as part of setuptools?

**Comment by simonjbeaumont** [comment]
Huh. It is there in the yum repo... I'll add it to the spec file.

**Comment by simonjbeaumont** [comment]
Once this is merged, all the necessary stuff will be in `/etc/bash_completion.d/`. All a user would need to do then is install `bash-completion` on their distro.

**Comment by euanh** [comment]
Looks good, thanks!

**Pull request merged**
