### PR TITLE
CA-202375: Build stunnel-4.15 against openssl-xs-devel-1.0.1e

### PR DESCRIPTION
**Pull request by phusl**
Signed-off-by: Phus Lu <phus.lu@citrix.com>

### CODE REVIEW

**Comment by phusl** [comment]
Related with https://github.com/xenserver/xen-api-backports/pull/22

**Comment by thomassa** [comment]
@phusl, do we still need this (and xenserver/xen-api-backports#22), or is it redundant if we are going to use the stunnel from the creedence-bugfix branch with the sanibel XenServer?

(If we do need it, I think this code-change looks fine.)

**Comment by robhoes** [comment]
@phusl Could you please answer Thomas' question? Thanks!

**Comment by phusl** [comment]
Sorry for late response @thomassa @robhoes 

Yes, I think we need this fix for sanibel-bugfix.

@thomassa understanding is right, if we use the stunnel from the creedence-bugfix, we do not need this fix.

But because this fix was already commited in sanibel-lcm, so I'd like to merge this fix to sanibel-bugfix branch also. :)

**Pull request merged**
