### PR TITLE
create-mock-config: Allow values in the [main] section of the

### PR DESCRIPTION
**Pull request by srowe**
'yum.conf' and 'dnf.conf' config options to be defined or overridden.

Signed-off-by: Simon Rowe <simon.rowe@citrix.com>

### CODE REVIEW

**Comment by MarkSymsCtx** [comment]
Is it worth adding an example to show how it could be used? e.g. reducing the verbosity/debug level of yum?

**Comment by srowe** [comment]
Do you want the example in the commit message?

**Comment by MarkSymsCtx** [comment]
I saw that you've done it on the internal ticket, that's good enough

**Comment by srowe** [comment]
I've put some actual examples on the ticket.

**Pull request merged**
