### PR TITLE
patchqueue: Fix patch generation with complex history

### PR DESCRIPTION
**Pull request by rosslagerwall**
git-format-patch is intended for use with simple linear histories which
means that it does not generate a consistent set of patches when the
history involves merges.  As an alternative, make a list of patches
similar to how git-format-patch does but include the diffs for merges
and ensure that the patch series is linear by following the first parent
only.

Signed-off-by: Ross Lagerwall <ross.lagerwall@citrix.com>

### CODE REVIEW

**Comment by rosslagerwall** [comment]
If you think this is too ugly, see #394...

**Comment by mseri** [comment]
I personally like #394 much more

**Comment by rosslagerwall** [comment]
Yes, me too.

**Comment by mseri** [comment]
I am closing this PR in favour of the other, but I want to wait @euanh opinion before doing anything with it

**Pull request closed without merging**
